### ISSUE TITLE
Implement missing text props in the SDF Text Renderer

### ISSUE THREAD

**Issue by pecoram** [lightning-js/renderer#107]
In the SDF Text Renderer the following props should be implemented:

- lineHeight
- verticalAlign
- ~~textBaseline~~ (moved to #134)
- maxLines
- overflowSuffix

**Comment by frank-weindel** [comment]
I have an implementation for everything except `textBaseline`. I've split that out to a separate issue #134. Please let me know @pecoram the importance of that property in the issue so we can prioritize it accordingly.

**Comment by pecoram** [comment]
Low priority
