### ISSUE TITLE
Standardize loaded events

### ISSUE THREAD

**Issue by wouterlucas** [lightning-js/renderer#12]
- Rename `txLoaded` and `textLoaded` event names to `loaded`
- Create two different [discriminated union](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions) payload types for both `txLoaded` and `textLoaded` events
  - A key named `type` used as the discriminator, which will be set to "texture" for what was originally `txLoaded` and "text" for what was originally `textLoaded`.

**Comment by chiefcll** [comment]
Right now there is a txLoaded and textLoaded event. Just a `loaded` event for both.
