### ISSUE TITLE
Renderer doesn't render anything, unless there is at least 1 text node or a node with a src or texture

### ISSUE THREAD

**Issue by michielvandergeest** [lightning-js/renderer#123]
Came accross this behaviour in Blits: when the entire App contains only elements without any src or texture (but with w/h and color), nothing get's rendered on the screen.

Ways to trigger a render loop:

- Adding at least 1 element with a `src`
- Adding at least 1 element with a `texture`
- Adding a Text component (even with no actual text to render)
- Changing something in the position of an Element after the initial render

Tracked down this behaviour and it doesn't seem Blits related. It can also be reproduced in the renderer, when turning off the overlay (this removes the text node that shows on each page, which is what makes the problem apparent).

To reproduce:

the alpha test (`?test=alpha&overlay=false`) doesn't render anything. The `?test=scaling&overlay=false` test _does_ render something (as it has text and images).

My assumption is that rendering is being skipped unless a node with a `src` or `texture` flips a switch to indicate something has to be rendered on screen.

**Comment by frank-weindel** [comment]
Thanks for the report. I'm able to reproduce it.
