### ISSUE TITLE
Issue with .png alpha handling

### ISSUE THREAD

**Issue by wouterlucas** [lightning-js/renderer#151]
PNG's can have an Alpha channel that needs to be handled with processing the texture data.

Without a fix this png:
![shines-top](https://github.com/lightning-js/renderer/assets/1534440/f7dc4db3-e7b4-4103-b1f9-c7c2c9747f3e)

will be handled as:
![Screenshot 2024-02-05 103705](https://github.com/lightning-js/renderer/assets/1534440/f679af5b-6fc7-4d77-9fcc-6bf57a4918eb)

while it should appear as:
![Screenshot 2024-02-05 103711](https://github.com/lightning-js/renderer/assets/1534440/e9314127-f60e-4b3d-89e2-a2bcc10b9433)

Setting the `premultiplyAlpha = true` on the texture data fixes this, however this will likely only need to happen when we're dealing with PNGs.

**Comment by frank-weindel** [comment]
Fixed with #153
