### ISSUE TITLE
Linear gradients performance

### ISSUE THREAD

**Issue by wouterlucas** [lightning-js/renderer#159]
Currently the linear gradient doesn't perform, this needs to be investigated.
Need to check if radial gradients have the same issue.

**Comment by toiladoong** [comment]
I have the same problem on TV, do you have a solution?

**Comment by chiefcll** [comment]
Yes - we removed it an used a png
https://github.com/lightning-js/solid-demo-app/blob/main/src/components/Background.tsx#L61

**Comment by chiefcll** [comment]
This can be closed out - @jfboeve - looks good thanks!
