### ISSUE TITLE
SDF Text: Presence of descenders results to higher reported height than when they are absent

### ISSUE THREAD

**Issue by suresh-gangumalla** [lightning-js/renderer#165]
Text rendering differnces between L2 and L3

I have verified text rendering using follwoing properties

-  font-family: Inter-Black MSDF 
- font size: 128
- line height 128

**In Lightning 3:**
 - Text  "Wonka", final rendered height is 146.28
 ![MSDF-Inter-Black-Wanka-Text-Rendering](https://github.com/lightning-js/renderer/assets/80351497/429cc6af-6bea-4a41-9cba-a18627e4ab08)
- Text "Migration", final rendered height is 170.66
![MSDF-Inter-Black-Migration-Text-Rendering](https://github.com/lightning-js/renderer/assets/80351497/2ad482b0-d721-45c1-874a-8f3a57efdf11)

**In Lightning 2**
- Text "Wonka" & "Migration" rendered with height of 192. (font-family: Inter Black TTF )

**Comment by frank-weindel** [comment]
Indeed you are right. Good timing for this because I've been dealing with hanging characters (aka descenders) all week 😄

**Comment by suresh-gangumalla** [comment]
Additional information

- sdfFontSize of "Inter-Black"is, 42 (info.size)
- fontSizeRatio = fontSize/sdfFontSize = 128/42 = 3.047461

## Current Render Height Calculation for MSDF type
### Single line texts
- "Wonka": 
  - Maximum character height  in "Wonka" is 48
  - Render height = 48 * fontSizeRatio = 146.285
- "Migration"
  - Maximum character height  in "Wonka" is 56
  - Render height = 56 * fontSizeRatio = 170.666

### Multiline Text:
- "Wonka\nWonka"
  - render height = 48 * fontSizeRatio  + 1 * lineHeight = 274.285
- "Wonka\nWonka\Wonka"
  - render height = 48 * fontSizeRatio  + 2 * lineHeight = 402.285
- "Migration\nMigration" = 56 * fontSizeRatio + lineHeight = 298.66
