### ISSUE TITLE
Sdf  maxLines not working with contain: "both"

### ISSUE THREAD

**Issue by pecoram** [lightning-js/renderer#183]
Using SDF maxLines works only with contain: "width" and not with contain: "both"

```
width: 870,
contain: "both",
maxLines: 2,
```
![image](https://github.com/lightning-js/renderer/assets/33352553/ffa456d4-022d-43c5-8604-a72342a79be2)

```
width: 870,
contain: "width",
maxLines: 2,
```
![image](https://github.com/lightning-js/renderer/assets/33352553/da738fb2-66db-48f1-b9cf-18ac97f7f292)

**Comment by chiefcll** [comment]
I saw this issue as well - not sure if it's valid though. Contain: both implies that you want it within a width and height, but you don't have a set height. Maxlines says draw 2 lines worth of text - We know height = lineHeight or fontSize * 2. 

What are you expecting in this case? I think maxlines should always 'win' and two lines should be rendered

**Comment by pecoram** [comment]
So the issue results in the fact that Canvas and SDF have two different behaviors
