### ISSUE TITLE
Text canvas renderer: `loaded` event re-fired when parent node is rotated

### ISSUE THREAD

**Issue by m-hall** [lightning-js/renderer#193]
I have a bit of a weird case of text elements are re-firing the `loaded` events when the parent element is rotating.

From what I can tell, the rotation is causing the `x` and `y` coords on the renderer to be re-evaluated, causing `invalidateVisibleWindowCache` to be called.
This appears to be a problem only with the canvas text renderer.

I believe it actually is reusing the same texture, and that the `x` and `y` coordinates are not relevant to rendering the text textures, and so while some parts of the window cache do need to be re-evaluated, the texture should still be considered valid, and not reset to a `loading` state.

For testing purposes, I created a clone of the solid template app that showcases the bug.
https://github.com/m-hall/solid-bug/

I have disabled the SDF renderer, and updated to the latest version of the renderer.
If you open the `Buttons` screen, I have made the buttons rotate when focused, and added logs to the `loaded` events for the text objects inside the buttons.

**Comment by chiefcll** [comment]
@frank-weindel - This is related to https://github.com/lightning-js/renderer/pull/184

In solid when text loads I set the width and height which causes the text to reload. There might be more to this bug but we should address that PR first
