### ISSUE TITLE
Feature: custom texture

### ISSUE THREAD

**Issue by elsassph** [lightning-js/renderer#230]
LightningJS 3 used to allow creating custom textures from a 2D canvas or image.

It doesn't seem possible yet.

**Comment by elsassph** [comment]
@wouterlucas I found it is in fact possible to create a custom texture by providing image data, which is easily obtained from a canvas:
```
renderer.createTexture("ImageTexture", { src: imageData })
```

Maybe close, or do you think there is a place for a simpler API?

**Comment by wouterlucas** [comment]
I think that's as simple as it gets for an image, however does that also cover all your needs with an externally created Canvas textures? Or did I misunderstand what you're trying to do.

**Comment by elsassph** [comment]
Though it may be a bit of an advanced use case, solution isn't very discoverable - may be worth considering documentation or a simplified API :)
