### ISSUE TITLE
Feature: granular memory management

### ISSUE THREAD

**Issue by elsassph** [lightning-js/renderer#233]
Current memory pressure logic is similar to lng2: when reaching a threshold, all the "invisible" or "out of bounds" textures are unloaded.

This is a simple but blunt instrument, causing much more texture reloading than needed.

In particular for remote images (`src`), as a lot of platforms do, there should be a MRU based memory management: instead of unloading all the textures possible, it should unload the "oldest" images until it reaches an intermediary level of memory pressure.

Note: in our lng2 app, we implemented such MRU logic, hacking into the Lightning internals to preserve the most recent images from being GC - the result is a MUCH improved experience, as rail images don't "randomly" unload themselves.

**Comment by wouterlucas** [comment]
We've been doing a stepped approach, first by ref, now by bounds. The idea of a LIFO (last in, first out) has been discussed, as well as a tier based logic (further away from the screen is going out first). 

In your implementation did you use 1 memory pressure setting for MRU and 1 for the existing LNG2 GC? Or is it 1 value that kicks in an approach by certain order?
And I assume the viewport is still taken into account when doing MRU based cleanups?

**Comment by elsassph** [comment]
Some notes about our approach:

- introduced an image helper to load images (mostly rail images) with `permanent` flag,
- register the image in a LIFO manager,
- LIFO manager has its own memory pressure set to 50% of the overall memory pressure,
- based on this separate memory pressure, `permanent` flag is removed to allow older images being collected if they are out of viewport.

**Comment by wouterlucas** [comment]
Nice, thanks for the extra details that's super helpful. Lets discuss this @frank-weindel @jfboeve @erikhaandrikman.

I guess its actually first in first out, as in the image that came in earlier has to go first. LIFO FIFO, it's a monday (MIFO, monday in friday out).

**Comment by elsassph** [comment]
Yes correct FIFO haha

**Comment by frank-weindel** [comment]
I think this approach makes a lot of sense. We could do this.

**Comment by elsassph** [comment]
Confused much, not FIFO, but LIFO or as I said initially, MRU based (were not out of bounds). If an image goes in bound it is considered fresh again.

**Comment by frank-weindel** [comment]
Implemented by #301
