### ISSUE TITLE
Feature: better tree shaking

### ISSUE THREAD

**Issue by elsassph** [lightning-js/renderer#234]
Currently Lng3 seem currently quite coupled.

- if we don't use threadx, we shouldn't load the functionality (it is currently always included),
- when canvas renderer will be available, only the right renderer should be loaded.

**Comment by wouterlucas** [comment]
Dupe of https://github.com/lightning-js/renderer/issues/160 

Moving it there.

**Comment by elsassph** [comment]
Ok @wouterlucas but the other ticket didn't cover "threadx"

**Comment by wouterlucas** [comment]
Fair point, adding it there.
