### ISSUE TITLE
Feature: DOM inspector "extras"

### ISSUE THREAD

**Issue by elsassph** [lightning-js/renderer#236]
DOM inspector is great for development, but insufficient for test automation.

Test automation needs to allow setting extra `dataset` fields, typically to provide a `testid` and mark the `focused` element.

**Comment by wouterlucas** [comment]
anything you set as a data field will be exposed as data-<key> attribute by the inspector. 

You can find it here:
https://github.com/lightning-js/renderer/blob/main/src/main-api/INode.ts#L423

**Comment by elsassph** [comment]
Awesome @wouterlucas

It's **mostly** working: one issue is that it doesn't seem possible to clear a data attribute.

Our automation uses `[data-focused]` to identify the focused element. Setting `data = { focused: '' }` can set the value, but I can't "unset" it.

**Comment by elsassph** [comment]
Also ideally it shouldn't set a field which has `undefined` value
