### ISSUE TITLE
Webpack compatibility

### ISSUE THREAD

**Issue by elsassph** [lightning-js/renderer#259]
### Issue

Webpack refuses the dynamic module loading approach in `src/render-drivers/utils.ts`:
```typescript
    module = (await import(
      coreExtensionModule /* @vite-ignore */
    )) as typeof module;
```
Following error appears in the console and overlays the app at run time:
```
WARNING in [...] Critical dependency: the request of a dependency is an expression
```
It is a rather annoying warning but doesn't break the app (provided extensions aren't used).

### Workaround

It is possible to silence the warning (loading extensions probably won't work):

```javascript
  plugins: [
    new webpack.ContextReplacementPlugin(/render-drivers/, (data) => {
      if (data.dependencies.length > 0) {
        delete data.dependencies[0].critical;
      }
      return data;
    }),
  ],
```
Source: https://medium.com/tomincode/hiding-critical-dependency-warnings-from-webpack-c76ccdb1f6c1

**Comment by elsassph** [comment]
Using `rspack`, to ignore the warning (it also probably won't work):
```javascript
module.exports = {
   /*...*/
   ignoreWarnings: [
    /the request of a dependency is an expression/,
    (warning) => true,
  ],
}
```
Source https://www.rspack.dev/config/other-options#ignorewarnings

**Comment by frank-weindel** [comment]
Since we're removing CoreExtensions along with ThreadX I think this issue can be closed. Please feel free to re-open if I'm mistaken.
