### ISSUE TITLE
Support TV Devices

### ISSUE THREAD

**Issue by chiefcll** [lightning-js/renderer#26]
Let's get the renderer running on TV devices. Currently they don't support offscreen canvas and FinalizationRegistry. Let's put those two things behind a feature flag or use detection and provide an alternative.

**Comment by wouterlucas** [comment]
Original "make it work" PR: https://github.com/lightning-js/renderer/pull/7

@frank-weindel is working on a long term PR to be able to only use FinalizationRegistry / OffscreenCanvas when the ThreadX driver is selected (as both are needed in that case).

**Comment by iamtabrezkhan** [comment]
Can I work on this? @wouterlucas

**Comment by wouterlucas** [comment]
of course @iamtabrezkhan!

**Comment by frank-weindel** [comment]
#46 should be enough to close this out for at least production Comcast devices. @iamtabrezkhan could you confirm from your perspective?

**Comment by wouterlucas** [comment]
Confirmed on discord, tested on XG2v2
