### ISSUE TITLE
Clamp the radius on the RadiusEffect shader

### ISSUE THREAD

**Issue by WillsonHaw** [lightning-js/renderer#283]
The radius value for the RadiusEffect shader is currently unbounded and can be set to a really high value. 

Here's how it looks in Lightning v3 with a radius of 55:

![image](https://github.com/lightning-js/renderer/assets/600962/1e4e2753-24b6-4ea9-933f-177564f9ee9d)

Here's how it looks in Web with the same values:
![image](https://github.com/lightning-js/renderer/assets/600962/ade69c3c-69d1-41e2-8301-76e7bcd381ce)

**Comment by M4tiz** [comment]
Looks like normalization of overlapping curves should be applied here. (specified by [CSS 3 spec](https://drafts.csswg.org/css-backgrounds/#corner-overlap) ). I can handle that :)

**Comment by wouterlucas** [comment]
Solved in #317
