### ISSUE TITLE
Image - support contain and cover options

### ISSUE THREAD

**Issue by chiefcll** [lightning-js/renderer#29]
In L2 we had a resizeMode:

resizeMode: {type: 'contain', w: 200, h: 200}}

**Comment by frank-weindel** [comment]
Similar to Lightning 2, this should likely be a new option added to the TextureOptions interface. 
https://github.com/lightning-js/renderer/blob/6e9dc53d0dd58a7c949e31d5d4db0770e8b01f5e/src/core/CoreTextureManager.ts#L72

**Comment by frank-weindel** [comment]
Implemented in #250
