### ISSUE TITLE
Few color props on a node are not resetting correctly

### ISSUE THREAD

**Issue by suresh-gangumalla** [lightning-js/renderer#304]
Few color props, like colorTop, colorBottom, ..., are not resetting correctly on updating node color

Sample example, 

```js
const item1 = renderer.createNode({
	x: 100,
	y: 200,
	width: 200,
	height: 200,
	colorTop: 0xefefefff,
	colorBottom:0xaaaaaaff,
	parent: node
})
```
```object
// Color properties on above node are,
color: 0,  
colorBl: 0xaaaaaaff, 
colorBottom: 0xaaaaaaff, 
colorBr: 0xaaaaaaff, 
colorLeft: 0, 
colorRight: 0, 
colorTl: 0xefefefff,
colorTop: 0xefefefff,
colorTr: 0xefefefff, 
```
```js
// after some timeout updating node color to "0xff0000ff"
item1.color = 0xff0000ff
```
```object
// Color properties on updated node are, 
color: 0xff0000ff
colorBl: 0xff0000ff
colorBottom: 0xaaaaaaff
colorBr: 0xff0000ff
colorLeft: 0
colorRight: 0
colorTl: 0xff0000ff
colorTop: 0xefefefff
colorTr: 0xff0000ff
```

Observed that, while ```colorTop``` & ```colorBottom```  properties still hold initial color values, the node is visually rendered with expected color.

**Comment by frank-weindel** [comment]
Thanks for the report. Low priority since it doesn't affect the end visual result. If anyone does work on this, please base it off of our `dev` branch (until we release it) since we've removed ThreadX (and it adds complexities to this)
