### ISSUE TITLE
RTT and parent alpha 

### ISSUE THREAD

**Issue by pecoram** [lightning-js/renderer#312]
When a child element with RTT (Render To Texture) is contained within a parent element that initially has an alpha value of 0, the child's texture does not update and remains invisible when the parent's alpha value is changed to 1.

Steps to Reproduce:

- Create a Parent element with an initial alpha value of 0.
- Add a child node to the Parent element. Ensure the child element has rtt set to true.
- Change the Parent element's alpha value from 0 to 1.

Expected Behavior:
The child element's texture should update and become visible when the Parent element's alpha value changes to 1.

Actual Behavior:
The child element's texture does not update and remains invisible, even though the Parent element's alpha value is set to 1.

**Comment by wouterlucas** [comment]
Fixed with https://github.com/lightning-js/renderer/pull/394
