### ISSUE TITLE
Image - Lazy load

### ISSUE THREAD

**Issue by chiefcll** [lightning-js/renderer#32]
Can we only load images that are in the viewport. There use to be a bounds to say load images when they are within X,Y Range of the viewport.

**Comment by wouterlucas** [comment]
Related to https://github.com/lightning-js/renderer/issues/49

Would images only load once they are in view or the provided bounds of a view?
How did Lightning 2.x do this?

**Comment by chiefcll** [comment]
In L2 - there was a boundsMargin property and it would only load things within the screen + margin.

Solution for L3 is set Alpha to 0 for now and it wont render those things. Eventually Renderer shouldnt render any nodes outside of the screen

**Comment by wouterlucas** [comment]
Will be solved as part of: https://github.com/lightning-js/renderer/issues/150
