### ISSUE TITLE
Request: Stage option to define quad buffer size

### ISSUE THREAD

**Issue by elsassph** [lightning-js/renderer#335]
LightningJS 2 defaults to 2Mb quad buffer, and it was configurable - an application typically would run fine even with 1Mb.

LightningJS 3 defaults to 4Mb and is missing a configuration option - configuration would allow saving a few Mbs of heap memory on the most constrained devices.

**Comment by marcel-danilewicz-consult-red** [comment]
Hi @elsassph,
should it be configurable at application level or somewhere else?

**Comment by elsassph** [comment]
I guess it should be a stage option like in L2 https://github.com/rdkcentral/Lightning/blob/dev/docs/RuntimeConfig/index.md

**Comment by marcel-danilewicz-consult-red** [comment]
Ok, I'll try to implement this.

**Comment by marcel-danilewicz-consult-red** [comment]
Done, PR: https://github.com/lightning-js/renderer/pull/337

**Comment by elsassph** [comment]
@marcel-danilewicz-consult-red you don't need to add a comment in the tickets, instead just write "Implements #337" in the PR description of the implementation and Github will automatically add a note here.
