### ISSUE TITLE
Properties absX and absY do not consider mount value

### ISSUE THREAD

**Issue by scailbc** [lightning-js/renderer#354]
Hello, if I'm not mistaken properties `absX` and `absY` in `CoreNode` should be the real position of the component in the page, calculated based on the X and Y values of the component itself and all its parents. The value should also consider other properties like `mount`, `scale`, `pivot` and `rotation` to calculate the exact position.

I did some test and this code works by handling the `mount` property;

```js
// src/core/CoreNode.ts row 1401
	get absX(): number {
		return (
			this.props.x -
			this.props.width * this.props.mountX +
			(this.props.parent?.absX || this.props.parent?.globalTransform?.tx || 0)
		);
	}

	get absY(): number {
		return this.props.y - this.props.height * this.props.mountY + (this.props.parent?.absY ?? 0);
	}
```

I'm trying to support mouse/magic remote, so the real position of the component is really important.

**Comment by scailbc** [comment]
Ok, I understand the point, but assuming the meaning of the 2 properties is this, I think they should at least support the `mount` property.
Can we fix this? I can make a PR if needed, maybe with an example page to easily test a few cases.

**Comment by wouterlucas** [comment]
Yeah of course, feel free to fire off a PR.

**Comment by scailbc** [comment]
Created PR #361 with the fix and the example file
