### ISSUE TITLE
Clipping is "delayed" in renderer 2.1 release

### ISSUE THREAD

**Issue by chiefcll** [lightning-js/renderer#371]
If you check out 

https://lightning-tv.github.io/solid-demo-app/#/

And keep pressing down. The images go outside of the clipped area and then disappear. Seems like with the new renderer 2.1 release clipping isn't happening every frame.

**Comment by chiefcll** [comment]
And sometimes breaks

<img width="1691" alt="image" src="https://github.com/user-attachments/assets/7dd7c8b2-3a67-4892-bd68-42a9a3b7b455">

**Comment by wouterlucas** [comment]
So in 2.1 a lot of operations are suppressed when it goes out of bounds to save excess CPU, as what's the point of doing changes to something that isn't visible anyway.

But it seems the bounds detection is going off early or it's racing with clipping when you're moving fast. Will have a look to see if this is simply a matter of reordering the operations or if we need to keep track of in bound changes vs outbound changes.

**Comment by WillsonHaw** [comment]
We are having the same issue in our React renderer

**Comment by wouterlucas** [comment]
> We are having the same issue in our React renderer

I'd recommend to stick to 2.0 until we figure this out.

**Comment by WillsonHaw** [comment]
Just to add to this, may or may not be related, but when animating things off screen or onto the screen, it will often either not animate at all or not show up at all.

**Comment by wouterlucas** [comment]
It is, its not properly propagating the change down from parents to children in all cases.
