### ISSUE TITLE
Nodes with alpha = 0 can't have their src changed

### ISSUE THREAD

**Issue by chiefcll** [lightning-js/renderer#372]
I have two background images which switch src and fade in / out from alpha 0 to 1. When the nodes go to alpha 0, the changes to node is ignored, even if I alpha is changed back to 1.

To reproduce:

create a node with a src
set node to alpha = 0
change the src
set node to alpha = 1

Node will not come back

**Comment by wouterlucas** [comment]
I've tried:

```ts
  const rocko = renderer.createNode({
    x: curX,
    y: curY,
    width: 181,
    height: 218,
    src: rockoImg,
    parent: testRoot,
  });

  await waitForTxLoaded(rocko);

  console.log('rocko loaded');

  rocko.alpha = 0;
  rocko.src = elevatorImg;
  rocko.alpha = 1;
````

And it shows an elevator for me, also tried timeouts to push it across ticks but all just behave fine. The only thing I noticed is that the TX Loaded doesn't fire for the second time. Could that be related to the issue you're seeing?

**Comment by chiefcll** [comment]
I think you need a set timeout in there to set the src after the renderer has a chance to update first

**Comment by elsassph** [comment]
Is it a case where you should animate to alpha 0.001 so the node is still "active" but generally invisible?

**Comment by wouterlucas** [comment]
> I think you need a set timeout in there to set the src after the renderer has a chance to update first

Yeah did both, in all cases the image updated to the new source just fine. So I can't replicate your issue, unless its about the TX Loaded event specifically. That doesn't seem to fire the second time.

**Comment by chiefcll** [comment]
```js
  const rocko2 = renderer.createNode({
    x: 200,
    y: 400,
    width: 181,
    height: 218,
    src: rocko,
    parent: testRoot,
  });

  setTimeout(() => {
    rocko2.alpha = 0;
  }, 1000);

  setTimeout(() => {
    rocko2.src = elevator;
  }, 1500);

  setTimeout(() => {
    rocko2.alpha = 1;
  }, 1800);
  ```

**Comment by wouterlucas** [comment]
You're not waiting for a loaded event though - that's the only difference I see. I've asked @Drulokia to see if he can reproduce the issue.

**Comment by chiefcll** [comment]
Don't need a loaded event - the elevator image will never appear. If I change the src at the same time I set alpha=0 it will change the image. Just can't do it during a separate cycle after the node is alpha 0.
