### ISSUE TITLE
Nodes are off by a pixel?

### ISSUE THREAD

**Issue by chiefcll** [lightning-js/renderer#373]
<img width="488" alt="Screenshot 2024-09-09 at 5 08 29 PM" src="https://github.com/user-attachments/assets/9d7ef458-1267-420e-9b89-9f3bd5c82603">

The black rectangle has 0, 0 abs positioning yet it's off by 1px on top and left in Chrome on desktop.
<img width="253" alt="Screenshot 2024-09-09 at 5 09 18 PM" src="https://github.com/user-attachments/assets/4f1d65ad-c3ae-4072-868a-91f1b7f342cb">

For structure, the yellow background image is the parent node with a src for image. The black rectangle is a child of a child node.

**Comment by chiefcll** [comment]
<img width="502" alt="image" src="https://github.com/user-attachments/assets/9aa6227f-cf96-4b07-89b3-33c905877b1f">

Here is the other corner as well. I thought this might be due to `devicePhysicalPixelRatio` but I updated that and still have this issue.

**Comment by wouterlucas** [comment]
Could not reproduce this using #391 - if you can find another way to setup the test that this does show, feel free to reopen.
