### ISSUE TITLE
Unnecessary heap allocations per frame for WebGL renderer.

### ISSUE THREAD

**Issue by itsjamie** [lightning-js/renderer#374]
https://github.com/rdkcentral/Lightning/issues/494

Reopening this issue which impacted Lightning 2 and still impacts Lightning 3.

https://github.com/lightning-js/renderer/blob/3a1fb19183a7b77914e31fff62b187bcf1484e7e/src/core/renderers/webgl/WebGlCoreShader.ts#L313-L320

https://github.com/lightning-js/renderer/blob/3a1fb19183a7b77914e31fff62b187bcf1484e7e/src/core/renderers/webgl/WebGlCoreShader.ts#L313-L320

The direct usage of the generic version of this function leads to each of those spread and rest operators creating new arrays that have to be garbage collected after each frame that includes these shaders.

If `...args` was replaced with `arguments` usage, it is possible you could keep the generic function without the explicit array being created from the rest operator usage.

For general applications this is fine, but the moment you have an animation that includes a re-render this can quickly grow into forcing many garbage collection cycles.

**Comment by itsjamie** [comment]
As recommended in the Lightning 2 ticket, adding the explicit GL functions that take stack parameters would also resolve this, such as `setUniform<1f,2f,3f,4f>` etc. This would mean having to use the proper value. I think it's a fine trade to have to use the explicit function. Anyway, as before, wanted to open the issue for discussion.

**Comment by wouterlucas** [comment]
Nice - thanks for resurfacing this @itsjamie !

Tagging @erikhaandrikman and @jfboeve - lets discuss this next sync.

**Comment by wouterlucas** [comment]
Something like this @itsjamie: https://github.com/lightning-js/renderer/commit/79f6181cce685af1b0278ecf3da45439c058daa6 ?

**Comment by itsjamie** [comment]
Exactly like that. 👍

**Comment by wouterlucas** [comment]
ok - will noodle on that and get a PR up soonish.
