### ISSUE TITLE
How do we use RTT?

### ISSUE THREAD

**Issue by chiefcll** [lightning-js/renderer#384]
I've looked through the examples for RTT - but in my app I can't get RTT to work how I'd expect it to work. For instance:

I have this contentblock with the text. Everything is rendered (added a color to it as well)
<img width="1061" alt="Screenshot 2024-09-16 at 8 35 40 PM" src="https://github.com/user-attachments/assets/3437fcde-a7b1-4cc7-b7dc-72ddc0fd7887">

If I select the node and set rtt = true, it disappears.

<img width="1554" alt="Screenshot 2024-09-16 at 8 36 00 PM" src="https://github.com/user-attachments/assets/ffb0089b-f00b-4911-a03a-8ac4b7a903e0">

I'd expect it to still be there and be able to copy the texture to another node. My goal is to simply take a set of nodes, turn it into a texture to duplicate it and then replace it with new content. Please let me know what I might be doing wrong...  I've tried setting color, rtt=true when node is created, zIndex...

**Comment by chiefcll** [comment]
@erikhaandrikman for awareness

**Comment by chiefcll** [comment]
Here is another example

<img width="1236" alt="image" src="https://github.com/user-attachments/assets/94059cb3-8ebb-4625-9fb0-f80ece53016b">

There was a square there - once it goes RTT you can see really small text where the box was before and a duplicate of it in the top left.

**Comment by erikhaandrikman** [comment]
Hi @chiefcll, can you share a minimal implementation directly in the render that we can run to reproduce this issue?

**Comment by chiefcll** [comment]
Here you go

```js
const props1 = {
    width: 1920,
    height: 1080,
    x: 0,
    y: 0,
    color: 0,
    parent: testRoot
  };
  const node1 = renderer.createNode(props1);

  const props2 = {
    x: 0,
    y: 0,
    width: 1920,
    height: 1080,
    color: 0,
    parent: node1
  };
  const node2 = renderer.createNode(props2);

  const props3 = {
    colorTop: 1147903743,
    colorBottom: 743406847,
    x: 0,
    y: 0,
    width: 1920,
    height: 1080,
    color: 0,

    parent: node2
  };
  const node3 = renderer.createNode(props3);

  const props4 = {
    y: 200,
    x: 170,
    width: 1750,
    height: 880,
    color: 0,
    parent: node3
  };
  const node4 = renderer.createNode(props4);

  const props5 = {
    height: 320,
    x: 0,
    y: 0,
    width: 1750,
    color: 0,
    parent: node4
  };
  const node5 = renderer.createNode(props5);

  const props6 = {
    data: { testId: "positioning" },
    width: 370,
    height: 320,
    scale: 1,
    color: 405488895,
    x: 0,
    y: 0,
    rtt: true,
    parent: node5,
  };
  const node6 = renderer.createNode(props6);
  ```

**Comment by wouterlucas** [comment]
Does this still happen for you with the latest fix to RTT? https://github.com/lightning-js/renderer/pull/421

**Comment by chiefcll** [comment]
Yes still having same issue.

**Comment by wouterlucas** [comment]
Might be related to https://github.com/lightning-js/renderer/issues/429

Does it go away when you turn the inspector off?

**Comment by chiefcll** [comment]
With inspector off - the text renders, but the color blocks are missing.
<img width="695" alt="image" src="https://github.com/user-attachments/assets/2c357a63-0a4b-4c35-960c-08363d4a4141">

With inspector on everything disappears (no text / no blocks).

**Comment by wouterlucas** [comment]
ah right - thats because properties of a rtt node are ignored. It's basically a holder node for the collapsed texture of its children. You'll have to wrap it accordingly.

**Comment by chiefcll** [comment]
That makes sense... If I understand correctly. Setting rtt on a node only RTT's it's children, and doesn't include the container? Which is why the box around it is not included in the texture? So we'd need to create another node above this to then RTT?

Could rtt apply to the container element and it's children?

**Comment by wouterlucas** [comment]
> That makes sense... If I understand correctly. Setting rtt on a node only RTT's it's children, and doesn't include the container? Which is why the box around it is not included in the texture? So we'd need to create another node above this to then RTT?

Correct.

> Could rtt apply to the container element and it's children?

I'm not sure if I understand the Q, can you elaborate. What do you mean by "rtt apply to the container element"?
If you enable RTT all its children will be collapsed into the node you enable it on as a texture.

**Comment by chiefcll** [comment]
If I put rtt on a node, I'd like that to be part of the texture that is created. For instance:

<img width="325" alt="image" src="https://github.com/user-attachments/assets/bb0f8b6f-ab23-4c6c-bc91-8712c272a586">

The blue container, if I put RTT on it, only the children are included in the tree. What I'm suggesting is the blue container would be included... So you'd have to move the RTT calculation up a node

**Comment by wouterlucas** [comment]
that would be odd, to have the created RTT texture live on a parent of the node you set the RTT on. If you then want to reference the created RTT texture and re-use that you would have to refer another node? that sounds counter intuitive.

Agree that this needs to be documented somewhere, there are some edge cases that need to be explained and we could always look to improve those as we run into specific implementations on where RTT is used. But it all depends on what the use case is (e.g. copying a texture versus using a reference) on a real UI / game.
