### ISSUE TITLE
Textures being freed?

### ISSUE THREAD

**Issue by chiefcll** [lightning-js/renderer#388]
This is running on my macbook - sometimes the FPS update counter text just goes away. Also the logos and text at the top left also is gone. This happens regularly on TV's but first time I've seen it on my macbook as well.

<img width="2782" alt="Screenshot 2024-09-18 at 6 05 37 PM" src="https://github.com/user-attachments/assets/81555cd8-8d17-427f-8cd7-c741253374a7">

**Comment by chiefcll** [comment]
I'm assuming the Texture Manager cleanup is too aggressive removing textures that are still nodes. Can it cleanup only textures that are no longer associated with attached nodes?

**Comment by chiefcll** [comment]
Further - The solid logo and the FPS info go to alpha 0 on certain pages and then go back to alpha 1. So I assume while they are not renderable, they are being deleted, but then when alpha=1 they don't come back.

**Comment by wouterlucas** [comment]
Could very well be that somehow the renderer thinks these are out of bounds with the latest changes to that. Atleast the behavior seems similar to other issues, how many layers do you wrap these in and does any of the layers have any dimensions on it?

Are those FPS counters MSDF text or sprites?

**Comment by chiefcll** [comment]
I think this is due to those textures being set to Alpha=0 when I go to examples page. When I go back to homepage they go back to alpha=1 but the textures are removed. I've updated my code to alpha=0.01 and now they don't get cleaned up.

The text is MSDF

**Comment by wouterlucas** [comment]
Interesting - @Drulokia was looking into that one and this might be valuable. Its very timing related and I couldnt reproduce it reliably on my mac weirdly enough.

**Comment by chiefcll** [comment]
Probably related to:
https://github.com/lightning-js/renderer/issues/372
