### ISSUE TITLE
Update strictBound when the size of a node changes

### ISSUE THREAD

**Issue by wouterlucas** [lightning-js/renderer#397]
Reported on Discord, strictBound should be recalculated if the dimensions of a node change or the bounds detection will work incorrectly.

**Comment by ChrisArasin** [comment]
Ran into an issue in Blits with a nested elements and clipping, but I'm guessing it may be the same issue here?
A child element with clipping seems to disappear when moving towards the right side of a parent element. 
(I can create a new issue if not) 

(left/right press here to test)
https://playground.lightningjs.io/#pEyjXNqiAiNc

**Comment by michielvandergeest** [comment]
I think that sounds like the issue that @wouterlucas fixed this morning in this PR: https://github.com/lightning-js/renderer/pull/398

**Comment by wouterlucas** [comment]
> Ran into an issue in Blits with a nested elements and clipping, but I'm guessing it may be the same issue here? A child element with clipping seems to disappear when moving towards the right side of a parent element. (I can create a new issue if not)
> 
> (left/right press here to test) https://playground.lightningjs.io/#pEyjXNqiAiNc

Hmm not sure about that, you're moving the parent node with clipping enabled and the parent itself is disappearing. However its not exiting a particular clipping area? 

Though it isn't nested, is that intentional?

**Comment by ChrisArasin** [comment]
So these are two identical children within a single parent. The children are having their x value animated on left/right. I would expect that neither should be clipped or go out of bounds. However, the child that has clipping=true seems to disappear. It felt like something was up with the bounds calculation of that child. 

I can test again once this fix is released and follow up.
