### ISSUE TITLE
Fix Snyk-Identified Security Issues

### ISSUE THREAD

**Issue by tuncayyildirtanuk** [lightning-js/renderer#448]
**Description:**

Sky utilizes a static code analysis tool called Snyk to identify and manage potential security vulnerabilities. Recent scans have flagged the following security issues:

<img width="1471" alt="Screenshot 2024-11-14 at 15 56 12" src="https://github.com/user-attachments/assets/061b81f8-3dc9-4a02-81ce-8a33f3cafb2d">

<img width="1471" alt="Screenshot 2024-11-14 at 15 56 02" src="https://github.com/user-attachments/assets/4842eb71-ba78-4167-94ed-7ef54612b429">

<img width="1470" alt="Screenshot 2024-11-14 at 15 55 51" src="https://github.com/user-attachments/assets/8ce1f853-7b88-4c4d-b5af-7e2888456a00">

<img width="1463" alt="Screenshot 2024-11-14 at 15 55 38" src="https://github.com/user-attachments/assets/47b45034-a0a7-4a4d-8b87-b86f7264c603">

<img width="1460" alt="Screenshot 2024-11-14 at 15 55 24" src="https://github.com/user-attachments/assets/bce4e605-15c2-4af6-a915-d5ad136f9a54">

**Request:**
Could you review and address these security vulnerabilities? Ensuring that we’re using secure, up-to-date packages and implementing recommended fixes is critical for maintaining the integrity of our codebase.

Steps to Reproduce (if applicable):

	1.	Run Snyk on the latest codebase.
	2.	Review the identified issues and prioritize fixes based on severity.

**Expected Outcome:**
All flagged security vulnerabilities are reviewed and addressed in accordance with Snyk’s recommendations.

**Comment by elsassph** [comment]
Not sure what validation could be done here: this is a low level library, `src` could be anything that makes sense for the app developer, so validation should be done at the app level.

**Comment by wouterlucas** [comment]
Fetch is a native browser API. This isn't a server side nodejs program as it gets executed on the browser, not on the server. They need to run Snyk with an appropriate profile as such that you do not get these messages for a browser app.

We can't do server side forgery from within JSC/V8/spidermonkey, else this would be a bug on the respective WebKit/Chromium/Mozilla. Which it aint.

If your security folks need an educational session about browsers, the difference between SSRF on a browser or a nodejs/deno/bun program and how SSRF's really work then feel free to reach out!
