### ISSUE TITLE
zIndex of parent doesn't get inherited by children

### ISSUE THREAD

**Issue by michielvandergeest** [lightning-js/renderer#47]
When setting the zIndex on a parent node, and omitting the zIndex on the children, the children don't seem to properly inherit the zIndex of the parent and the parent is placed _on top_ of it's children.

The expected behaviour would be that the children inherit the same zIndex as their parent.

This issue can easily be recreated by removing the zIndex of `rectThree` in the zIndex example (`examples/tests/zIndex.ts`)

**Comment by chiefcll** [comment]
@erikhaandrikman - When we discussed this it was up to the framework to do this. Right now Solid is adding zIndex to all elements to properly place elements. 
https://github.com/lightning-js/solid/blob/main/src/core/node/index.ts#L399

**Comment by michielvandergeest** [comment]
This seems to be fixed in v0.6.0 - not sure it was on purpose or just a happy side effect of the renderer optimizations 😄 

@MLangendijk, I believe you were also waiting for this fix - does the latest Blits (which contains renderer 0.6.0) solve the issue you were running into?

**Comment by MLangendijk** [comment]
@michielvandergeest my specific case indeed works with 0.6.0, the calcZIndex function added looks to have solved this :)
