### ISSUE TITLE
SDF Text: height(with contain both) doesn't crop correctly

### ISSUE THREAD

**Issue by michielvandergeest** [lightning-js/renderer#48]
This is perhaps a rare case, but I noticed that when setting the height attribute on a text node and using contain both, the height doesn't seem to crop exactly correct (depending on the text and text size).

See the image below, the bottom part of the `q` goes slightly over the background (which is a parent node that has the same height as set for the height of the text node).

<img width="741" alt="image" src="https://github.com/lightning-js/renderer/assets/8299035/38920eb1-b172-4088-a3a5-e5eb3cec5ba7">

**Comment by wouterlucas** [comment]
is this still valid? @frank-weindel @michielvandergeest ?

**Comment by frank-weindel** [comment]
@michielvandergeest Is this `canvas` text? I assumed it was SDF but I can't reproduce it there.

**Comment by frank-weindel** [comment]
Never mind I ended up discovering a similar issue with `canvas` text and assumed that's the issue you were reporting here. I have been able to reproduce this issue with the `sdf` text renderer.
