### ISSUE TITLE
Events to know when a node is in viewport

### ISSUE THREAD

**Issue by wouterlucas** [lightning-js/renderer#49]
Events to trigger when a node is entering a viewport, would need the concept of "a viewport" to begin with.

Tracking for: 
* When a node is visible or not
* (nice to have) Track how far it is positioned out of the viewport
*

**Comment by elsassph** [comment]
We are using custom bounds margin to control images preloading in a few important places.

**Comment by elsassph** [comment]
Maybe related: L2 would consider an element `alpha` 0 or `visible` false to be inactive. `alpha` 0 has been more an annoyance than a help in that regard, but `visible` false should deactivate an element and release its textures.
