### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by JohnPaulHarold** [lightning-js/renderer#53]
Hello.

Is there anywhere that explains and details the browser/device compatibility of this library? The same could be asked of "blitz" also.

**Comment by chiefcll** [comment]
Our current bottom limit is Chrome 49 due to the usage of Proxies in both Solid and Blits. (TV devices from 2018+)
Though these can be mitigated and allow for a Chrome 38/39 setup (avoid mergeProps in Solid).

**Comment by JohnPaulHarold** [comment]
@chiefcll Thank you. 

Is the plan for this to be made somewhere more public than here when you move out of beta? 

Also, are you viewing this in terms of browser compatibility baselines (Chrome _n_ upwards), or planning to perhaps devise a more nuanced matrix of tested devices. Such as "Tizen >= 2018, tested"?

**Comment by chiefcll** [comment]
There are dozens of devices out there. We're initially targeting Chrome 49 and hoping to go back as far as Chrome 38. We're hoping the community can test against different devices and we should probably create a README with a list of known working devices.

**Comment by chiefcll** [comment]
There are dozens of devices out there. We're initially targeting Chrome 49 and hoping to go back as far as Chrome 38. We're mentioning browser versions because we know certain devices have certain browsers installed. We're hoping the community can test against different devices and we can create a list for folks to submit to.

**Comment by wouterlucas** [comment]
> @chiefcll Thank you.
> 
> Is the plan for this to be made somewhere more public than here when you move out of beta?
> 
> Also, are you viewing this in terms of browser compatibility baselines (Chrome _n_ upwards), or planning to perhaps devise a more nuanced matrix of tested devices. Such as "Tizen >= 2018, tested"?

We'll include this as part of documentation/website updates. For now most of this is discussed here or through Discord :)
