### ISSUE TITLE
Clipping and scale together are not compatible

### ISSUE THREAD

**Issue by pecoram** [lightning-js/renderer#54]
When clipping and scale are put together, scale does not work.

An example: 

```
BackgroundContainer: {
        borderRadius: 6,
        color: "#00ff73",
        scale: 0,
        focus: {
            scale: 1.5,
        },
    },
```
<img width="425" alt="Screenshot 2023-10-13 alle 12 12 55" src="https://github.com/lightning-js/renderer/assets/33352553/61ff03df-2f04-4db4-9d76-e3b1305c2c56">

```
BackgroundContainer: {
        borderRadius: 6,
        color: "#00ff73",
        scale: 0,
        clipping: true,
        focus: {
            scale: 1.5,
        },
    },
```
<img width="374" alt="Screenshot 2023-10-13 alle 12 14 06" src="https://github.com/lightning-js/renderer/assets/33352553/ca45a633-3aa3-4233-b9d8-7286d5dc52b6">

**Comment by frank-weindel** [comment]
Thanks for the report! We will work on this soon.
