### ISSUE TITLE
Setting focused width and height by ref fails

### ISSUE THREAD

**Issue by pecoram** [lightning-js/renderer#55]
This is a borderline use case.
In my example each row has elements of different sizes
<img width="800" alt="Screenshot 2023-10-16 alle 11 26 23" src="https://github.com/lightning-js/renderer/assets/33352553/6e5be9da-5b2d-4e50-a9b9-f1a1e06fd8eb">

```
<View
	onFocus={others.onFocus}
	width={others.width}
	height={others.height}
	style={styles.VideoItem}
	forwardStates
	ref={videoItemRef}
>
	<View forwardStates style={styles.BackgroundContainer} ref={backgroundContainerRef} />
	<View style={styles.Border} ref={borderRef} />
</View>
```

```
	Border: {
		borderRadius: 12,
		border: { width: FOCUS_BORDER, color: "#ffffff" },
		alpha: 0,
		scale: 0,
		focus: {
			scale: FOCUS_SCALE,
			alpha: [1, { duration: 100, delay: 0, timing: "easy-in-out" }],
		},
	},
	BackgroundContainer: {
		borderRadius: 6,
		clipping: true,
		color: "#00ff73",
		focus: {},
	}
```

since the scale and clipping doesn't work together I tried to set the width and the height of the element via ref.focus.width and ref.focus.height 

```
const FOCUS_BORDER: number = 6;
const FOCUS_SCALE: number = 1.05;

const focusWidth = others.width - FOCUS_BORDER;
const focusHeight = others.height - FOCUS_BORDER;

if (backgroundContainerRef?.focus) {
    backgroundContainerRef.focus.width = (focusWidth + 1) * FOCUS_SCALE;
    backgroundContainerRef.focus.height = (focusHeight + 1) * FOCUS_SCALE;
    backgroundContainerRef.focus.x = (focusWidth * (1 - FOCUS_SCALE)) / 2;
    backgroundContainerRef.focus.y = (focusHeight * (1 - FOCUS_SCALE)) / 2;
}
```
When I focus one of the larger items, it takes the sizes of the smaller one

<img width="747" alt="Screenshot 2023-10-16 alle 11 38 58" src="https://github.com/lightning-js/renderer/assets/33352553/a773a67b-a63c-49d7-a35f-e3eea6fa7cbf">

with v0.3.5 this scenario worked

**Comment by chiefcll** [comment]
So I think you got this wrong from what you should be doing with Solid Lightning...

1. The focus on the class is a state that gets applied when the element receives focus. You also can't change the style object or any of the properties after the element gets created as its shared between all elements.

You should just be setting the properties directly on `backgroundContainerRef` and not setting it on focus
```js
backgroundContainerRef.width = (focusWidth + 1) * FOCUS_SCALE;
    backgroundContainerRef.height = (focusHeight + 1) * FOCUS_SCALE;
    backgroundContainerRef.x = (focusWidth * (1 - FOCUS_SCALE)) / 2;
    backgroundContainerRef.y = (focusHeight * (1 - FOCUS_SCALE)) / 2;

```

**Comment by pecoram** [comment]
I didn't understand why the focus is shared between all elements but I fixed by setting ref.width and ref.height via onFocus and resetting them through onBlure
