### ISSUE TITLE
Absolute position relative to the parent. (ex: "right: 10, bottom: 10")

### ISSUE THREAD

**Issue by chiefcll** [lightning-js/renderer#66]
I'd like the renderer to support 
left, top, right, bottom

Since all elements are basically absolute positioned to it's parent, it would be nice to support these props to make it easier to do layout in core renderer rather than at solid or blits layer. Even if these are just shortcuts to changing the mount value these would be really helpful.

**Comment by anthony9187** [comment]
+1 it'd do a lot to match existing web APIs and make the UI easier to reason about

**Comment by wouterlucas** [comment]
currently there are no plans to support relative position or flex box like functionality inside the renderer. Easiest is to keep this at the app framework side for now.
