### ISSUE TITLE
Unable to render on Comcast Xi5 box

### ISSUE THREAD

**Issue by iamtabrezkhan** [lightning-js/renderer#69]
Hey guys,
On Xi5 box, app is unable to render properly.
I have tried both solid demo app and the example from renderer repo.
Please find below the recordings of how it appears.

> Solid Demo App
https://github.com/lightning-js/renderer/assets/22201739/74e5a99e-9f28-4517-8ebd-aa51c018c6d0

> [Example](https://github.com/lightning-js/renderer/tree/main/examples) from renderer repo
https://github.com/lightning-js/renderer/assets/22201739/c558ea6c-8a3c-4143-b518-afdd9e674a67

There are no errors in the console.

**Comment by wouterlucas** [comment]
hi @iamtabrezkhan we're still trying to reproduce this, looking to get a Xi5 up and running for us to test this with.

**Comment by iamtabrezkhan** [comment]
Hey @wouterlucas, any update on this issue?

**Comment by wouterlucas** [comment]
Found my Xi5, will try to hook it up this week. If that doesn’t pan out I’m planning to use browserstack and see how far back we can go on older webkit/chrome installs.

**Comment by wouterlucas** [comment]
@iamtabrezkhan though I haven't been able to get my Xi5 to work we where able to test on a variet of Xfinitiy and other RDK devices. Seems to work just fine, can you retest with the latest examples app to see if it still occurs?

**Comment by iamtabrezkhan** [comment]
@wouterlucas Sure, I will try to run again.

**Comment by wouterlucas** [comment]
> @wouterlucas Sure, I will try to run again.

any luck?

**Comment by iamtabrezkhan** [comment]
Haven't tried it yet. Will try tonight 🤞

**Comment by iamtabrezkhan** [comment]
Hey, I am getting error while installing dependencies in solid-demo-app.
Steps I took:
1. Clone the repository
2. Run `npm i`

Got the follwing error:
```sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: solid-demo-app@1.0.0
npm ERR! Found: vite@5.0.12
npm ERR! node_modules/vite
npm ERR!   dev vite@"^5.0.12" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^4.4.9" from @lightningjs/vite-plugin-import-chunk-url@0.3.0
npm ERR! node_modules/@lightningjs/vite-plugin-import-chunk-url
npm ERR!   dev @lightningjs/vite-plugin-import-chunk-url@"^0.3.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/void/.npm/_logs/2024-02-06T19_42_09_644Z-eresolve-report.txt
```
Node version: 20.10.0
Npm version: 10.2.3

**Comment by chiefcll** [comment]
I'll check this out tomorrow. We've been using pnpm - you may want to delete the package.lock and try again
Also the demo app is hosted:
https://lightning-js.github.io/solid-demo-app/#/

**Comment by iamtabrezkhan** [comment]
Thanks @chiefcll @wouterlucas 
Just tried the hosted app on the Xi5-P box, and it is indeed working properly 👏🏻 🙇🏻 (and it is the same box on which I was trying to run the app earlier when I opened this issue)
Although there seems to be some scaling problem but I think we can close this issue!

![WhatsApp Image 2024-02-08 at 12 01 13 AM](https://github.com/lightning-js/renderer/assets/22201739/35d1d682-d7f1-43bd-ae88-b64e8ab6cfae)

**Comment by chiefcll** [comment]
The app is hard coded for 1080p - @wouterlucas - I'd love some logic to calculate best resolution to use on devices 🙏
